#!/bin/sh

CFG="%{F$(xgetres runel.info_fg)}"
CHD="%{F$(xgetres runel.info_hd)}"

text=".data[0] | \"${CHD}COVID-19%{F-} Italy  ${CFG}|%{F-}  \
${CHD}Confirmed%{F-}  ${CFG}\\(.cases)%{F-}  \
${CHD}Recovered%{F-}  ${CFG}\\(.recovered)%{F-}  \
${CHD}Deaths%{F-}  ${CFG}\\(.deaths)%{F-}  \
${CHD}Active%{F-}  ${CFG}\\(.active)%{F-}\""

i=0
while [ "${i}" -lt 10 ]; do
    curl -s 'https://corona-stats.online/Italy?format=json' | jq -r "${text}"
    sleep 1
    i="$((i + 1))"
done
