#!/bin/sh

CFG="%{F$(xgetres runel.info_fg)}"
CHD="%{F$(xgetres runel.info_hd)}"

text=".data[0] | \"${CHD}COVID-19 Italy  ${CFG}|  \
${CHD}Confirmed  ${CFG}\\(.cases)  \
${CHD}Recovered  ${CFG}\\(.recovered)  \
${CHD}Deaths  ${CFG}\\(.deaths)  \
${CHD}Active  ${CFG}\\(.active)\""

i=0
while [ "${i}" -lt 10 ]; do
    curl -s 'https://corona-stats.online/Italy?format=json' | jq -r "${text}"
    sleep 1
    i="$((i + 1))"
done
