#!/usr/bin/dash

CFG="%{F\\\\$(xgetres runel.info_fg)}"
CHD="%{F\\\\$(xgetres runel.info_hd)}"

text="${CHD}F%{F-}  ${CFG}\${freq}MHz%{F-}  \
${CHD}C%{F-}  ${CFG}\${cpu}%%%{F-}  \
${CHD}T%{F-}  ${CFG}\${acpitemp}°C%{F-}  \
${CHD}R%{F-}  ${CFG}\${mem}%{F-}  \
${CHD}S%{F-}  ${CFG}\${swap}%{F-}  \
${CHD}FsR%{F-}  ${CFG}\${fs_free /}%{F-}  \
${CHD}FsH%{F-}  ${CFG}\${fs_free /home}%{F-}  \
\${if_mounted /mnt/second_partition}${CHD}FsW%{F-}  ${CFG}\${fs_free /mnt/second_partition}%{F-}  \${endif}\
${CHD}IOr%{F-}  ${CFG}\${diskio_read /dev/sda}%{F-}  \
${CHD}IOw%{F-}  ${CFG}\${diskio_write /dev/sda}%{F-}  \
${CHD}P%{F-}  ${CFG}\${running_processes}/\${processes}%{F-}\
\${if_empty \${battery_time}}\${else}  ${CHD}B%{F-}  ${CFG}\${battery_time}%{F-}\${endif}"

exec conky -i 60 -t "${text}"
