#!/usr/bin/dash

CFG="%{F\\\\$(xgetres runel.info_fg)}"
CHD="%{F\\\\$(xgetres runel.info_hd)}"

text="${CHD}I%{F-}  ${CFG}\${gw_iface}%{F-}  \
${CHD}G%{F-}  ${CFG}\${gw_ip}%{F-}\
\${if_up wlo1}  ${CHD}WiFi%{F-}  ${CFG}\${addr wlo1}%{F-}  \
${CHD}Sd/u%{F-}  ${CFG}\${downspeedf wlo1}/\${upspeedf wlo1}Kbs%{F-}  \
${CHD}Td/u%{F-}  ${CFG}\${totaldown wlo1}/\${totalup wlo1}%{F-}\${endif}\
\${if_up eno1}  ${CHD}Wired%{F-}  ${CFG}\${addr eno1}%{F-}  \
${CHD}Sd/u%{F-}  ${CFG}\${downspeedf eno1}/\${upspeedf eno1}Kbs%{F-}  \
${CHD}Td/u%{F-}  ${CFG}\${totaldown eno1}/\${totalup eno1}%{F-}\${endif}"

exec conky -i 60 -t "${text}"
