#!/usr/bin/dash

CFG="%{F\\\\$(xgetres runel.info_fg)}"
CHD="%{F\\\\$(xgetres runel.info_hd)}"

text="${CHD}N%{F-}  ${CFG}\${wireless_essid wlo1}%{F-}  \
${CHD}M%{F-}  ${CFG}\${wireless_ap wlo1}%{F-}  \
${CHD}Q%{F-}  ${CFG}\${wireless_link_qual wlo1}/\${wireless_link_qual_max wlo1}%{F-}  \
${CHD}F%{F-}  ${CFG}\${wireless_freq wlo1}%{F-}  \
${CHD}B%{F-}  ${CFG}\${wireless_bitrate wlo1}%{F-}  \
${CHD}T%{F-}  ${CFG}\${wireless_mode wlo1}%{F-}"

exec conky -i 60 -t "${text}"
