#!/usr/bin/dash

CFG="%{F\\\\$(xgetres runel.info_fg)}"
CHD="%{F\\\\$(xgetres runel.info_hd)}"

text="${CHD}N  ${CFG}\${wireless_essid wlo1}  \
${CHD}M  ${CFG}\${wireless_ap wlo1}  \
${CHD}Q  ${CFG}\${wireless_link_qual wlo1}/\${wireless_link_qual_max wlo1}  \
${CHD}F  ${CFG}\${wireless_freq wlo1}  \
${CHD}B  ${CFG}\${wireless_bitrate wlo1}  \
${CHD}T  ${CFG}\${wireless_mode wlo1}"

exec conky -i 60 -t "${text}"
