#!/bin/sh

set -o nounset
set -o errexit

if test "$#" = 0; then
    printf 'This is a automatic installer.\n'
    printf 'Make sure that this repo is linked to %s/nixpkgs.\n\n' "${XDG_CONFIG_HOME:-${HOME}/.config}"
    printf 'To install nixpkgs\n'
    printf '$ %s nixpkgs\n\n' "$0"
    printf 'To install 20.09 release of home-manager:\n'
    printf '$ %s 20.09\n\n' "$0"
    printf 'To install unstable branch of home-manager:\n'
    printf '$ %s unstable\n\n' "$0"
    printf 'To install:\n'
    printf '$ %s install\n\n' "$0"
    exit 1
fi

case "$1" in
    nixpkgs)
        nix-channel --remove nixpkgs
        nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
        nix-channel --update
        printf '>>> Now logout!\n'
        ;;
    unstable)
        nix-channel --remove home-manager
        nix-channel --add "https://github.com/nix-community/home-manager/archive/master.tar.gz" home-manager
        nix-channel --update
        printf '>>> Now logout!\n'
        ;;
    20.09)
        nix-channel --remove home-manager
        nix-channel --add "https://github.com/nix-community/home-manager/archive/release-20.09.tar.gz" home-manager
        nix-channel --update
        printf '>>> Now logout!\n'
        ;;
    install)
        mkdir -p ../nix
        grep max-jobs ../nix/nix.conf || echo "max-jobs = auto" >> ../nix/nix.conf

        nix-shell -p git --run "nix-shell '<home-manager>' -A install"

        nix-collect-garbage -d
        nix-store --optimise -v

        printf '\n\n>>> ALL SET!\n\n'
        printf 'Logout and dont forget to activate mu with:\n'
        printf '$ mu init --my-address=my@mail1 --my-address=my@mail2\n'
        ;;
    *)
        printf 'Invalid arguments! Run %s without arguments for help.' "$0"
        exit 1
esac
