#!/bin/sh

set -o nounset
set -o errexit

if test "$#" = 0; then
    printf '>>> This is an automatic installer.\n'
    printf '>>> Make sure that this repo is linked to %s/nixpkgs\n' "${XDG_CONFIG_HOME:-${HOME}/.config}"
    printf '>>> and that you have done nixos-rebuild switch --upgrade\n\n'
    printf '>>> First install home-manager channel:\n'
    printf '>>> $ %s channel\n\n' "$0"
    printf '>>> Then logout and run:\n'
    printf '>>> $ %s install\n\n' "$0"
    exit 1
fi

case "$1" in
    channel)
        nix-channel --remove "home-manager"
        nix-channel --add "https://github.com/nix-community/home-manager/archive/release-20.09.tar.gz" "home-manager"
        nix-channel --update
        printf '>>> Now logout!\n'
        ;;
    install)
        mkdir -p ../nix
        grep max-jobs ../nix/nix.conf || echo "max-jobs = auto" >> ../nix/nix.conf

        nix-shell -p git --run "nix-shell '<home-manager>' -A install"

        printf '\n\n>>> ALL SET!\n\n'
        printf '>>> Logout and dont forget to activate mu with:\n'
        printf '$ mu init --my-address=my@mail1 --my-address=my@mail2\n'
        ;;
    *)
        printf '>>> Invalid arguments! Run %s without arguments for help.' "$0"
        exit 1
esac
