#!/bin/sh

alias myip='echo "$(curl -s ipecho.net/plain)"'
alias turncardoff='sudo tee /proc/acpi/bbswtich <<<OFF'
alias turncardon='sudo tee /proc/acpi/bbswtich <<<ON'
alias nvidia-settings='optirun -b none nvidia-settings -c :8 --config="$XDG_CONFIG_HOME"/nvidia/settings'
alias mmount='sudo mount -o gid=100,uid=1000'
alias pwngdb='gdb -x /usr/share/pwndbg/gdbinit.py'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias dash='dash -E'

# Disable ctrl+s pause
stty -ixon

PS1='$? $(whoami) '
