pkgs: with pkgs; ''
  (in-package :stumpwm)

  (setf *rmount* "${scripts}/bin/rmount")
  (setf *rumount* "${scripts}/bin/rumount")
  (setf *acpi* "${acpi}/bin/acpi")
  (setf *mpc* "${mpc_cli}/bin/mpc")
  (setf *notify-sound* "${scripts}/bin/notify_sound")
  (setf *brightnessctl* "${brightnessctl}/bin/brightnessctl")
  (setf *xdg-user-dir* "${xdg-user-dirs}/bin/xdg-user-dir")
  (setf *scrot* "${scrot}/bin/scrot")
  (setf *image-clipboard* "${scripts}/bin/image_clipboard")
  (setf *df* "${coreutils}/bin/df")
  (setf *pass* "${pass-otp}/bin/pass")
  (setf *rimer* "${rimer}/bin/rimer")
  (setf *rimer-callback* "${scripts}/bin/rimer_callback")
  (setf *uxterm* "${xterm}/bin/uxterm")
  (setf *pulsemixer* "${pulsemixer}/bin/pulsemixer")
  (setf *htop* "${htop}/bin/htop")
  (setf *nload* "${nload}/bin/nload")
  (setf *firefox* "${firefox}/bin/firefox")
  (setf *chromium-incognito* "${ungoogledChromiumIncognito}/bin/chromium-incognito")
  (setf *telegram-desktop* "${tdesktop}/bin/telegram-desktop")
  (setf *emacs* "${myEmacs}/bin/emacs")
  (setf *notify-send* "${libnotify}/bin/notify-send")
  (setf *amixer* "${alsaUtils}/bin/amixer")
  (setf *qutebrowser* "${qutebrowser}/bin/qutebrowser")

  (uiop:launch-program '("systemctl" "--user" "start" "random-background.service"))
''
