#!/bin/sh

print_duration() {
    ffprobe -v quiet -of json -show_entries format=duration "${1:?}" \
        | jq '.format.duration | tonumber | round'
}

if [ "${#}" -eq 0 ]; then
    while read -r video; do
        print_duration "${video}"
    done
else
    for video in "${@}"; do
        print_duration "${video}"
    done
fi
