(defpackage #:swm-config
  (:use #:cl)
  (:local-nicknames (#:swm #:stumpwm))
  (:import-from #:uiop #:launch-program)
  (:export #:init))
(in-package #:swm-config)

(defun init ()
  ;;                 '("black"   "red"     "green"   "magenta" "blue"    "yellow"  "cyan"    "white"))
  (setf swm:*colors* '("#101010" "#ff0086" "#00c918" "#ad00a1" "#3777e6" "#aba800" "#1faaaa" "#ffffff"))
  (setf swm:*mouse-focus-policy* :click)
  (swm:set-prefix-key (swm:kbd "C-z"))
  (mapc #'swm:update-color-map swm:*screen-list*)
  (swm:set-font "-*-terminus-medium-r-*-*-24-*-*-*-*-*-iso10646-1")
  (swm:clear-window-placement-rules)
  (launch-program '("systemctl" "--user" "start" "random-background.service"))
  (swm-config.reverse-im:init))
