(in-package :stumpwm)

(defvar *rmount* "rmount")
(defvar *rumount* "rumount")
(defvar *acpi* "acpi")
(defvar *amixer* "amixer")
(defvar *mpc* "mpc")
(defvar *notify-sound* "notify_sound")
(defvar *notify-send* "notify-send")
(defvar *xbacklight* "xbacklight")
(defvar *xdg-user-dir* "xdg-user-dir")
(defvar *scrot* "scrot")
(defvar *image-clipboard* "image_clipboard")
(defvar *df* "df")
(defvar *pass* "pass")
(defvar *rimer* "rimer")
(defvar *rimer-callback* "rimer_callback")
(defvar *uxterm* "uxterm")
(defvar *pulsemixer* "pulsemixer")
(defvar *htop* "htop")
(defvar *nload* "nload")
(defvar *firefox* "firefox")
(defvar *qutebrowser* "qutebrowser")
(defvar *chromium-incognito* "chromium-incognito")
(defvar *telegram-desktop* "telegram-desktop")
(defvar *emacs* "emacs")
