#!/usr/bin/sh

# general settings
BW=2
bspc config border_width          "${BW}"
bspc config window_gap            "-${BW}"
for side in top right bottom left; do
    bspc config "${side}_padding" "${BW}"
done

if [ -n "${RUNEL_WM_NAME}" ]; then
    panel_id="$(xdo id -a "${RUNEL_WM_NAME}")"
    if [ -n "${panel_id}" ]; then
        panel_pad="$(xwininfo -id "${panel_id}" | awk '/Height:/ {print $2}')"
        if [ -n "${panel_pad}" ]; then
            bspc config top_padding "$((panel_pad + BW))"
        fi
    fi
fi

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config pointer_follows_focusfalse
bspc config automatic_scheme longest_side
bspc config initial_polarity second_child

# colors
bspc config active_border_color   "$( xgetres 'bspwm.active_border_color' )"
bspc config normal_border_color   "$( xgetres 'bspwm.normal_border_color' )"
bspc config presel_feedback_color "$( xgetres 'bspwm.presel_feedback_color' )"
bspc config focused_border_color  "$( xgetres 'bspwm.focused_border_color' )"

bspc monitor --reset-desktops H B V C M R T S
bspc query --desktops --names | xargs -I'{}' bspc desktop '{}' --layout monocle

# rules
bspc rule --remove '*'
bspc rule --add qutebrowser     desktop=B
bspc rule --add firefox         desktop=B
bspc rule --add Firefox         desktop=B
bspc rule --add IceCat          desktop=B
bspc rule --add Navigator       desktop=B
bspc rule --add brave-browser   desktop=B
bspc rule --add Brave-browser   desktop=B
bspc rule --add "Tor Browser"   desktop=B state=pseudo_tiled
bspc rule --add TelegramDesktop desktop=C
bspc rule --add mpv             desktop=V follow=off
bspc rule --add Zathura     state=tiled
bspc rule --add Emacs:emacs:Ediff state=floating
bspc rule --add Emacs:emacs state=tiled

# bspc config external_rules_command "${XDG_CONFIG_HOME:?}/bspwm/external_rules"
