#!/bin/dash

# wid=$1
# class=$2
# instance=$3
# monitor=$4
# desktop=$5
# node_selectors=$6

# case "$instance" in
#     urxvt)
#         title="$(xtitle "$wid")"
#         case "$title" in
#             "mpv-audio")
#                 echo "desktop=V locked=on follow=on"
#                 ;;
#         esac
#         ;;
# esac

# # Get current focused window id
# fwid="$(bspc query --nodes --node focused.automatic)"

# # If not empty
# if [ -n "${fwid}" ]; then
#     # Get window stats
#     # Get width and height and compare them. Output split_direction on largest
#     xwininfo -id "${fwid}" -stats | \
#         awk '/Width:/ {w=$2}
#              /Height:/ {h=$2}
#              END {d="south"; if (w > h) d="west"; print "split_dir=" d}'
# fi
