#!/bin/sh

get_current() {
    amixer -D pulse sget Master \
        | grep --color=never 'Front Left:' \
        | cut -d" " -f 7 \
        | tr -d '[]%' \
        | awk '
{
    mod = $1 % 10
}

mod >= 5 {
    print $1 + (10 - mod)
}

mod < 5 {
    print $1 - mod
}
'
}

print_menu() {
    seq -f '%0.f%%' 100 -10 10
    printf 'toggle\n2%%+\n2%%-'
}

get_new() {
    print_menu | rofi -dmenu -lines 13 -p "Number (0 - 100)" -select "$(get_current)"
}

amixer -D pulse sset Master "$(get_new)"
