{
  inputs,
  pkgs,
  ...
}: {
  home.packages =
    [
      inputs.epkg-amded.packages.${pkgs.system}.amded
    ]
    ++ (with pkgs; [
      acpi
      # addictionsTracker
      alsaUtils
      ascii
      aspell
      aspellDicts.en
      aspellDicts.en-computers
      aspellDicts.en-science
      aspellDicts.it
      aspellDicts.ru
      aspellDicts.uk
      atool
      bind
      binutils
      brave
      brave-incognito
      brightnessctl
      browser
      calibre
      cloc
      cpulimit
      discord
      djvulibre
      dmenu
      enchant
      exiftool
      fd
      ffmpeg
      file
      filename_put_duration
      flameshot
      format_seconds
      ghostscript
      gimp
      go-mtpfs
      graphicsmagick
      hunspell
      hunspellDicts.en_US-large
      hunspellDicts.it_IT
      hunspellDicts.ru_RU
      hunspellDicts.uk_UA
      image-dired-external-viewer
      image_clipboard
      imagemagick
      interval_timer
      inxi
      iw
      iwgtk
      ledger
      lem
      libjpeg
      libnotify
      libreoffice
      make_backup
      mediainfo
      mkpasswd
      mpc_cli
      mpvi
      nload
      notifiers
      ntfs3g
      nuspell
      p7zip
      pandoc
      parted
      pdftk
      perlPackages.JSONPP
      pinentry
      pueue
      pulsemixer
      pwgen
      qrencode
      qrshow
      rar
      recode_video
      resize_video
      ripgrep
      rsync
      scrot
      sdcv
      shellcheck
      simplescreenrecorder
      sort_videos_by_duration
      speedtest-cli
      stalonetray
      strip_video
      stumpwm
      nsxiv
      telegram-desktop
      tor-browser-bundle-bin
      transmission
      udiskie
      unzip
      video_seconds
      wally-cli
      wget
      woof
      wormhole-william
      xclip
      xdg-user-dirs
      xkb-switch
      xterm
      xz
      yt-dlp
      ytdl
      ytdla
      ytdlap
      ytdli
      ytdlm
      ytdlmp
      ytdlp
      zip
      zoom-us
    ]);
}
