#!/bin/dash
cat <<- _EOF_
#define base00 #${color00}
#define base01 #${color01}
#define base02 #${color02}
#define base03 #${color03}
#define base04 #${color04}
#define base05 #${color05}
#define base06 #${color06}
#define base07 #${color07}
#define base08 #${color08}
#define base09 #${color09}
#define base0A #${color10}
#define base0B #${color11}
#define base0C #${color12}
#define base0D #${color13}
#define base0E #${color14}
#define base0F #${color15}
_EOF_
