#!/bin/bash
for file in "$@"; do
    dur=$(video_duration "$file" | xargs format_duration | tr -t ':' '_' | sed -Ee 's/^[0_]+//')
    ext=${file##*.}
    len=$((${#ext} + 1))
    printf -v newfile "%s.d%s.%s" "${file:0:-${len}}" "$dur" "$ext"
    mv -v "$file" "$newfile"
done
