#!/bin/sh
[ -z "${1}" ] && notify-send "Url is empty"
link="${1:?provide url}"
link="${link:?}"

get_formats() {
    columns='format_id,width,height,ext,filesize,vcodec,acodec'
    jq_format=".formats[] | (\"\(.$(echo "${columns}" | sed 's/,/)|\\(./g'))\")"
    #                                                     "," -> ")|\(."
    youtube-dl --no-color --dump-json "${link}" \
        | jq --raw-output "${jq_format}" \
        | column --table --separator '|'
}

select_format() {
    dmenu -p "Select format" -l 19
}

menu='480x640
audio only
768x1366
360x480
240x320
144x256
select video'
format="$(printf "%s" "${menu}" | dmenu -p "mpv")"

case "${format:?}" in
    768x1366)
        chosen_format='(bestvideo+bestaudio/best)[height<=?768][width<=?1366]'
        ;;
    480x640)
        chosen_format='(bestvideo+bestaudio/best)[height<=?480][width<=?640]'
        ;;
    360x480)
        chosen_format='(bestvideo+bestaudio/best)[height<=?360][width<=?480]'
        ;;
    240x320)
        chosen_format='(bestvideo+bestaudio/best)[height<=?240][width<=?320]'
        ;;
    144x256)
        chosen_format='(bestvideo+bestaudio/best)[height<=?144][width<=?256]'
        ;;
    "audio only")
        chosen_format='bestaudio/best'
        ;;
    "select video")
        selected_format="$(get_formats | select_format | awk '{print $1}')"
        chosen_format="${selected_format:?}+bestaudio/${selected_format:?}/best"
        ;;
esac

pause="$(printf '%s\n\n' --pause | dmenu -p "Start paused?")"

exec mpv "${link}" ${pause} \
     --profile=gui \
     --load-unsafe-playlists \
     --ytdl-raw-options=yes-playlist= \
     --ytdl-format="${chosen_format:?}" \
     --loop-playlist=inf
