#!/bin/sh

MUSIC_DIRECTORY="${XDG_MUSIC_DIR:-${HOME}/Music}"

[ -d "${MUSIC_DIRECTORY}" ] || exit 1

select_directory() {
    find "${MUSIC_DIRECTORY}" -type d ! -wholename "${MUSIC_DIRECTORY}" \
        | cut -c "$((${#MUSIC_DIRECTORY} + 2))-" \
        | sort \
        | dmenu -p "Select directory" -l 19
}

selected_dir="$(select_directory)"

output="${MUSIC_DIRECTORY}/${selected_dir}/%(title)s.%(ext)s"
# args="--audio-format mp3 --embed-thumbnail"
# args="--audio-format mp3"
# args="--audio-format opus"

if [ "$(printf 'no\nyes' | dmenu -p 'Playlist?')" = yes ]; then
    output="${MUSIC_DIRECTORY}/${selected_dir}/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s"
    args="${args} --yes-playlist"
fi


exec youtube-dl --format bestaudio/best --extract-audio --output "${output}" ${args} "$@"
