#!/bin/sh

[ -z "${1}" ] && notify-send "Url is empty"
url="${1:?provide url}"

get_formats() {
    columns='format_id,width,height,ext,filesize,vcodec,acodec'
    jq_format=".formats[] | (\"\(.$(echo "${columns}" | sed 's/,/)|\\(./g'))\")"
    #                                                     "," -> ")|\(."
    youtube-dl --no-color --dump-json "${url}" \
        | jq --raw-output "${jq_format}" \
        | column --table --separator '|'
}

select_format() {
    dmenu -p "Select format" -l 19
}

if test "false" = "$(pueue status --json | jq '.groups | has("ytdl")')"; then
    pueue group add --parallel 3 ytdl
fi

case "$(printf "video\naudio\nmusic\nselect video" | dmenu -p "Download")" in
    video)
        pueue add --escape --group=ytdl -- ytdl "$url"
        ;;
    audio)
        pueue add --escape --group=ytdl -- ytdla "$url"
        ;;
    music)
        pueue add --escape --group=ytdl --immediate -- ytdlam "$url"
        ;;
    "select video")
        selected_format="$(get_formats | select_format | awk '{print $1}')"
        chosen_format="${selected_format:?}+bestaudio/${selected_format:?}/best"
        pueue add --escape --group=ytdl -- ytdl -f "$chosen_format" "$url"
        ;;
esac
