#!/bin/bash
for file in "$@"; do
    dur=$(video_duration "$file" | format_duration | cut -d" " -f1)
    ext=${file##*.}
    len=$((${#ext} + 1))
    printf -v newfile "%s - %s.%s" "${file:0:-${len}}" "$dur" "$ext"
    mv -v "$file" "$newfile"
done
