#!/bin/sh

exec awk -F"${2:- }" -v pos="${1:-1}" -v OFS="${3:-${2:- }}" '
{
    $pos = sprintf("%02d:%02d:%02d",
                   ($pos / (60 * 60)),
                   ($pos / 60) % 60,
                   $pos % 60)
    print $0
}
'
