#!/bin/sh

# make_backup /directory

set -o nounset

exit_error() { echo "${1}" >&2; exit "${2:-1}"; }

get_directory() {
    lsblk -nrpo "name,type,size,mountpoint" \
        | awk '$2=="part"&&$4!~/\/boot|\/home$|SWAP/&&length($4)>1{printf "%s %s\n",$3,$4}' \
        | dmenu -p "Select partition" -l 10 \
        | cut -d" " -f 2-
}

directory="${1:-$(get_directory)}"
[ ! -d "${directory:?provide directory}" ] && exit_error "${directory} is not a directory"

rsync --delete --delete-excluded --archive --verbose --partial --progress --relative \
      --backup --backup-dir="${directory%/}/backup" --suffix="$(date '+.~%Y%m%d')" \
      --exclude='lost+found' --exclude="${directory}" \
      ~/Documents ~/Downloads ~/Music ~/Pictures ~/Videos ~/archives ~/org \
      ~/.authinfo.gpg ~/.gnupg ~/.mail ~/.password-store ~/.ssh \
      /mnt/second_partition ~/.config/nixpkgs ~/.local/share/emacs \
      "${directory%/}/current"
