{
  pkgs,
  inputs,
  ...
}: {
  programs.emacs = {
    enable = true;
    extraPackages = epkgs:
      (
        map (flake: inputs."epkg-${flake}".packages.${pkgs.system}.default) [
          "amded"
          "cyrillic-dvorak-im"
          "dired-atool-transient"
          "dired-tags"
          "pueue"
          "rx-widget"
          "sdcwoc"
          "tempo-extra"
        ]
      )
      ++ (with epkgs; [
        affe
        apheleia
        async
        avy
        avy-embark-collect
        cargo
        cider
        clojure-mode
        consult
        csharp-mode
        csproj-mode
        csv-mode
        djvu
        dotnet
        dumb-jump
        ebdb
        edit-indirect
        eglot
        embark
        embark-consult
        emmet-mode
        envrc
        flymake-collection
        htmlize
        ipretty
        json-navigator
        ledger-mode
        link-hint
        magit
        marginalia
        nix-mode
        notmuch
        nov
        orderless
        org
        org-contrib
        org-mime
        org-roam
        pcmpl-args
        pdf-tools
        php-mode
        rainbow-mode
        reverse-im
        rg
        rust-mode
        sly
        sly-asdf
        sly-quicklisp
        sql-indent
        sqlup-mode
        transmission
        tree-sitter
        tree-sitter-langs
        verb
        vertico
        vlf
        web-mode
        wgrep
      ]);
  };
}
